configMapGenerator:
- files:
  - application.yml
  name: template-for-aa-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: ceappacr.azurecr.io/template-for-aa
  newTag: "202410290135"
- name: cepgstapacr.azurecr.io/cloud-sample
  newTag: "202408120727"
